In [7]:
import pandas as pd
import statistics
import csv
import numpy as np

df= pd.read_csv('BostonHousing.csv' , usecols=['medv'])

medv = df['medv'].to_numpy()

def mean(array):
    sum = 0
    #iterates through the array and adds all the elements up
    for i in range(0,len(array)):
        sum = sum + array[i]
    #converts the mean to cm
    return (sum/len(array))

def greatest(array):
    max = array[0]
    #compares each element in the array and replaces the max accordingly
    for i in range(0,len(array)):
        if array[i]>max:
            max = array[i]
    return max
    
def least(array):
    min = array[0]
    month = 0
    #compares each element in the array and replaces the min accordingly
    for i in range(0,len(array)):
        if array[i]<min:
            min = array[i]
    return min
def statRange(array):
    return max(array)-min(array)

def variance(array):
    var = 0
    #puts each value in the equation for variance
    for i in range(0,len(array)):
        var = var + (array[i]-mean(array))**2
    return var/(len(array)-1)
#returns the square root of variance function
def sd(array):
    return variance(array)**(1/2)
def mode(array):
    occurancesArray = [0]*len(array)
    #compares the current element with all the elements in the array and places the # of occurances in an array 
    for i in range(0,len(array)):
        occurances = 0;
        current = array[i]
        for j in range(0,len(array)):
            if(current == array[j]):
                occurances = occurances + 1
        occurancesArray[i] = occurances 
    #returns the element with the greatest occurances  
    for i in range(0,len(occurancesArray)):
        if(greatest(occurancesArray)==occurancesArray[i]):
            return(array[i])

def percentile(percent,array):
    #calculates the index that the percentage would be at
    n = (int)(percent/100 * (len(array)))
    array.sort()
    for i in range(0,len(array)):
        if(i == n):
            return array[i]

print ("The mean of BostonHousing:", end =" "),print (mean(medv))
print ("The max of BostonHousing:", end =" "),print (greatest(medv))
print ("The min of BostonHousing:", end =" "),print (least(medv))
print ("The range of BostonHousing:", end =" "),print (statRange(medv))
print ("The variance of BostonHousing:", end =" "),print (variance(medv))
print ("The standard deviaion of BostonHousing:", end =" "),print (sd(medv))
print ("The mode of BostonHousing:", end =" "),print (mode(medv))
print ("The 40 percentile of BostonHousing:", end =" "),print (percentile(40, medv))
print ("The 80 percentile of BostonHousing:", end =" "),print (percentile(80, medv))

The mean of BostonHousing: 22.532806324110698
The max of BostonHousing: 50.0
The min of BostonHousing: 5.0
The range of BostonHousing: 45.0
The variance of BostonHousing: 84.5867235940986
The standard deviaion of BostonHousing: 9.19710408737982
The mode of BostonHousing: 50.0
The 40 percentile of BostonHousing: 19.7
The 80 percentile of BostonHousing: 28.2


(None, None)

In [43]:
import numpy as np

A = [0]*4
#creates an array based on the text file lines
with open('input.txt', 'r') as f:
    array = np.array([[float(num) for num in line.split(' ')] for line in f])
    
#creates array for each row but does not incude the last element
for i in range(0,len(array)):
    A[i] = np.array([array[i][0],array[i][1],array[i][2],array[i][3]])
A_inverse = np.linalg.inv(A)

#numbers after the = sign
last = np.array([array[0][4],array[1][4],array[2][4],array[3][4]])
#gets the dot product of A inverse and the numbers after the = sign
solution = np.dot (A_inverse , last)

print("The System of equations is \nx + 2y - 3z + 4w = 12\n2x + 2y - 2z + 3w = 10\n0 + y + z + 0 = -1\nx - y + z - 2w = -4\n")
print("The Matrix is represented by\n", array)
print("\nThe Solution is", solution)

The System of equations is 
x + 2y - 3z + 4w = 12
2x + 2y - 2z + 3w = 10
0 + y + z + 0 = -1
x - y + z - 2w = -4

The Matrix is represented by
 [[ 1.  2. -3.  4. 12.]
 [ 2.  2. -2.  3. 10.]
 [ 0.  1.  1.  0. -1.]
 [ 1. -1.  1. -2. -4.]]

The Solution is [ 1.  0. -1.  2.]
